-- Portable DDL: runs on PostgreSQL 14+ and on H2 in MODE=PostgreSQL.
CREATE TABLE patient (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mrn_system   VARCHAR(255),
    mrn          VARCHAR(64)  NOT NULL,
    family_name  VARCHAR(255) NOT NULL,
    given_names  VARCHAR(255),
    gender       VARCHAR(16),
    birth_date   DATE,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_patient_mrn UNIQUE (mrn)
);

CREATE INDEX ix_patient_family_name ON patient (family_name);

CREATE TABLE observation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status              VARCHAR(32)  NOT NULL,
    code_system         VARCHAR(255) NOT NULL,
    code                VARCHAR(64)  NOT NULL,
    code_display        VARCHAR(255),
    patient_id          BIGINT       NOT NULL,
    effective_date_time TIMESTAMP WITH TIME ZONE,
    value_quantity      NUMERIC(18, 4),
    value_unit          VARCHAR(32),
    CONSTRAINT fk_observation_patient FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE
);

CREATE INDEX ix_observation_patient_code ON observation (patient_id, code);
